app/models.py
from app import db
from flask_bcrypt import Bcrypt

bcrypt = Bcrypt()


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(60), unique=True, nullable=False)
    password = db.Column(db.String(30), unique=True, nullable=False)

    def __init__(self, email, password):
        self.email = email
        self.set_password(password)  # chama set_password para criar o hash da senha

    def set_password(self, password):
        # Lógica para criar o hash da senha e armazená-lo no atributo password_hash
        self.password = bcrypt.generate_password_hash(password).decode("utf-8")

    def check_password(self, password):
        # Lógica para verificar a senha
        return bcrypt.check_password_hash(self.password, password)

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy


# Cria uma instancia do SQLAlchemy e Migrate
db = SQLAlchemy()
migrate = Migrate()


# Cria e configura uma instancia do aplicativo Flask
def create_app():
    # importa User para garantir que o SQLAlchemy e o Flask-Migrate tenham acesso ao modelo
    from app.models import User
    from app.routes import forms_bp

    app = Flask(__name__)

    # Configuraçao do SQLAlchemy e banco de dados
    app.config["SECRET_KEY"] = "##25!!73##"
    app.config[
        "SQLALCHEMY_DATABASE_URI"
    ] = "mysql+mysqlconnector://root:6273!Ric#@localhost/meubanco"
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    app.config["MYSQL_HOST"] = "localhost"
    app.config["MYSQL_USER"] = "root"
    app.config["MYSQL_PASSWORD"] = "6273!Ric#"
    app.config["MYSQL_DB"] = "meubanco"

    # Inicializa o SQLAlchemy e o Migrate com o aplicativo Flask
    db.init_app(app)
    migrate.init_app(app, db)

    # Registra os Blueprints no aplicativo
    app.register_blueprint(forms_bp, url_prefix="/")

    return app

app/routes.py
from flask import render_template, redirect, url_for, Blueprint, request, session

forms_bp = Blueprint("forms", __name__, template_folder="templates")


def is_authenticated():
    return "email" in session  # Verifica se o endereço de email está na sessão


@forms_bp.route("/login", methods=["GET", "POST"])
def login():
    from app.models import User

    if request.method == "POST":
        email = request.form["email"]
        senha = request.form["senha"]

        # Verifica se o usuario já existe no banco de dados:
        existing_user = User.query.filter_by(email=email).first()

        # verifica se a senha corresponde:
        if existing_user and existing_user.check_password(senha):
            session["email"] = email
            return redirect(url_for("index.home"))
        else:  # Se não corresponde envia uma mensagem de erro e volta para a página de login:
            mensagem = "Credenciais Invalidas. Tente Novamente"
            return render_template("login.html", mensagem=mensagem)

    return render_template("login.html")


@forms_bp.route("/registro", methods=["GET", "POST"])
def registro():
    from app.models import User
    from app import db

    if request.method == "POST":
        novo_email = request.form["novo_email"]
        nova_senha = request.form["nova_senha"]
        conf_senha = request.form["conf_senha"]

        # Verifica se o usuario já existe no banco de dados:
        existing_user = User.query.filter_by(email=novo_email).first()
        if existing_user:
            mensagem = "Este email já está registrado. Vincule outro endereço de email"
            return render_template("registro.html", mensagem=mensagem)

        confirm = nova_senha != conf_senha
        if confirm:
            mensagem = "As senhas digitadas não correspondem. Tente novamente"
            return render_template("registro.html", mensagem=mensagem)

        # cria o novo usuario e adiciona no banco de dados:
        new_user = User(email=novo_email, password=nova_senha)
        new_user.set_password(nova_senha)  # cria o hash da senha
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for("forms.login"))

    return render_template("registro.html")

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="static/login.css">
  <title>Login</title>
</head>
<body class="pagina-grid">
  <style>
    .mensagem {
      color: red;
    }
  </style>

  {% if mensagem %} 
  <p class="mensagem">{{ mensagem }}</p>
  {% endif %}

  <div class="wrapper">
    <div class="titulos">
      <div class="titulo">Login Form</div>
    </div>
    <div class="formulario">
      <form class="login" method="Post"> 
        <div class='signup-link'>Not a Member? <a href="{{ url_for('forms.registro') }}">Signup Now</a></div>
        <div class="campo">
          <label for="usuario">Email Adress:</label>
          <input type="text" placeholder="Email Adress"  id="Email" name="Email" required>
        </div>
        <div class="campo">
          <label for="senha">Password:</label>
          <input type="password" placeholder="Password" id="senha" name="senha" required>  
        </div>
        <div class="forgot-link"><a href="#">Forgot Password?</a></div>
        <div class="campo btn">  
          <div class="botao"></div>
          <input type="submit" value="Login">
        </div>
      </form>
    </div>
  </div>
</body>
</html>

app/templates/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="static/registro.css">
  <title>Registro</title>
</head>
<body>
  <style>
    .mensagem {
      color: red;
    }
  </style>
    
  {% if mensagem %}
  <p class="mensagem">{{ mensagem }}</p>
  {% endif %}

  <div class="wrapper">
    <div class="titulos">
      <div class="titulo">Signup Form</div>
    </div>
    <div class="formulario">
      <form class="signup" method="post" action="/forms/registro">
        <div class="login-link">Have an account? <a href="{{ url_for('forms.login') }}">Sign in Now</a></div>
        <div class="campo">
          <label for="novo_usuario">Email Adress:</label>
          <input type="text" placeholder="Email Adress" id="novo_email" name="novo_email" required>
        </div>
        <div class="campo">
          <label for="nova_senha">Password:</label>
          <input type="password" placeholder="Password" id="nova_senha" name="nova_senha" required>
        </div>
        <div class="campo">
          <label for="conf_senha">Confirm Password:</label>
          <input type="password" placeholder="Confirm Password" id="conf_senha" name="conf_senha" required>
        </div>
        <div class="campo btn">
          <div class="botao"></div>
          <input type="submit" value="signup">         
        </div>       
      </form>
    </div>
  </div>
</body>
</html>